version: '3.7'

services:
  postgres:
    container_name: 'gobarber-postgres'
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gobarber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - /home/julio/Desktop/Projects/Nodejs/gobarber/data:/var/lib/postgresql/data

  redis:
    container_name: 'gobarber-redis'
    image: redis:alpine
    ports:
      - "6379:6379"

  mongo:
    container_name: 'gobarber-mongo'
    image: mongo
    ports:
      - "27017:27017"

  app:
    depends_on:
      - postgres
      - redis
      - mongo
    build: .
    ports:
      - "3333:3333"
    command: yarn build
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
      MONGO_URL: mongodb://mongo:27017/gobarber
